import * as deepsea from "./terrain/deepsea/deepsea.js"
import * as grassland from "./terrain/grassland/grassland.js"
import * as hills from "./terrain/hills/hills.js"
import * as sea from "./terrain/sea/sea.js"
import * as terrain from "./terrain/terrain.js"
import * as coal_ore from "./res/coal_ore/coal_ore.js"
import * as copper_ore from "./res/copper_ore/copper_ore.js"
import * as iron_ore from "./res/iron_ore/iron_ore.js"
import * as resLayer from "./res/resLayer.js"
import * as stone_ore from "./res/stone_ore/stone_ore.js"
import * as tree from "./res/tree/tree.js"
import * as assembling_machine_1 from "./entity/assembling_machine_1/assembling_machine_1.js"
import * as assembling_machine_2 from "./entity/assembling_machine_2/assembling_machine_2.js"
import * as player from "./entity/player/player.js"
import * as empty from "./entity/empty/empty.js"
import * as coal from "./item/coal/coal.js"
import * as iron from "./item/iron/iron.js"
import * as copper from "./item/copper/copper.js"
import * as stone from "./item/stone/stone.js"
import * as wood from "./item/wood/wood.js"
import * as wooden_stick from "./item/wooden_stick/wooden_stick.js"
import * as circuit from "./item/circuit/circuit.js"
import * as gear from "./item/gear/gear.js"
import * as stone_furnace from "./entity/stone_furnace/stone_furnace.js"
import * as iron_plate from "./item/iron_plate/iron_plate.js"
import * as copper_plate from "./item/copper_plate/copper_plate.js"
import * as copper_cable from "./item/copper_cable/copper_cable.js"
import * as burner_miner from "./entity/burner_miner/burner_miner.js"
import * as iron_stick from "./item/iron_stick/iron_stick.js"
import * as chest from "./entity/chest/chest.js"
import * as belt1 from "./entity/belt1/belt1.js"
import * as belt2 from "./entity/belt2/belt2.js"
import * as belt3 from "./entity/belt3/belt3.js"
var elements = [deepsea, grassland, hills, sea, terrain, coal_ore, copper_ore, iron_ore, resLayer, stone_ore, tree, assembling_machine_1, 
    assembling_machine_2, player, empty, coal, wood, wooden_stick, stone_furnace, stone, circuit, gear, iron_plate, iron, copper, copper_plate, 
    copper_cable, burner_miner, iron_stick, chest, belt1, belt2, belt3 ]
export default elements